#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/opera-proxy

opera_proxy_instance() {
    local section="$1"
    local enabled args

    config_get_bool enabled "$section" 'enabled' '0'
    [ "$enabled" -eq 0 ] && return 0

    config_get args "$section" 'args' ''

    procd_open_instance
    procd_set_param command "$PROG"

    [ -n "$args" ] && procd_append_param command $args

    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

start_service() {
    config_load 'opera-proxy'
    config_foreach opera_proxy_instance 'instance'
}

service_triggers() {
    procd_add_reload_trigger "opera-proxy"
}